# Generated by Django 3.1.5 on 2021-02-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='short_name',
        ),
        migrations.AddField(
            model_name='company',
            name='codename',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shortname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
