# Generated by Django 3.1.5 on 2021-02-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('DD', models.DateField(blank=True, null=True)),
                ('MD', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ('-DD',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=5, unique=True)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Other', 'Other')], default='Customer', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Lead', 'Lead'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('VAT_Number', models.CharField(blank=True, default='', max_length=40)),
                ('tax_status', models.CharField(blank=True, default='', max_length=100)),
                ('office_notes', models.TextField(blank=True, default='')),
                ('order_notes', models.TextField(blank=True, default='')),
                ('manufacture_notes', models.TextField(blank=True, default='')),
                ('delivery_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order')),
                ('OD', models.DateField(blank=True, null=True, verbose_name='Order Date')),
                ('LD', models.DateField(blank=True, null=True, verbose_name='Lead Date')),
                ('LD_S', models.BooleanField(default=False, help_text='Strict', verbose_name='Lead Date Strict')),
                ('CD', models.DateField(blank=True, null=True)),
                ('CD_C', models.BooleanField(default=False, help_text='confirmed')),
                ('delivered', models.BooleanField(default=False)),
                ('invoiced', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('order_notes', models.TextField(blank=True, default='---press update to copy STD notes---')),
                ('manufacture_notes', models.TextField(blank=True, default='---press update to copy STD notes---')),
                ('delivery_notes', models.TextField(blank=True, default='---press update to copy STD notes---')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('xx', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='erp.company')),
            ],
            options={
                'ordering': ('LD',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('print', models.BooleanField(default=False)),
                ('cut', models.BooleanField(default=False)),
                ('weld', models.BooleanField(default=False)),
                ('stuff', models.BooleanField(default=False)),
                ('pack', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('SKU', models.CharField(blank=True, default='', max_length=20)),
                ('barcode', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='erp.company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='erp.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('xprice', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('xnotes', models.TextField(blank=True, default='')),
                ('print', models.PositiveSmallIntegerField(default=0)),
                ('cut', models.PositiveSmallIntegerField(default=0)),
                ('weld', models.PositiveSmallIntegerField(default=0)),
                ('stuff', models.PositiveSmallIntegerField(default=0)),
                ('pack', models.PositiveSmallIntegerField(default=0)),
                ('printed', models.BooleanField(default=False, verbose_name='complete')),
                ('cutx', models.BooleanField(default=False)),
                ('welded', models.BooleanField(default=False)),
                ('stuffed', models.BooleanField(default=False)),
                ('packed', models.BooleanField(default=False)),
                ('tally', models.CharField(blank=True, default='', max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='erp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='erp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('office_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=60)),
                ('contact_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='erp.company')),
            ],
            options={
                'ordering': ('company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BatchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchorder', to='erp.batch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batchorder', to='erp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVOICE', 'Invoice'), ('DELIVERY', 'Delivery')], default='INVOICE', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='erp.company')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='MPrintOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='MyDummy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.dummy',),
        ),
        migrations.CreateModel(
            name='MyOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='OrderItem_adminview',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'type', 'title'), name='unique_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_item'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_contact'),
        ),
        migrations.AddConstraint(
            model_name='batchorder',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='unique_batch_order'),
        ),
    ]
