# Generated by Django 3.1.7 on 2021-03-29 19:57

from django.db import migrations, models
import django.db.models.deletion
import erp.models.order
import erp.models.orderitem


class Migration(migrations.Migration):

    #replaces = [('erp', '0001_squashed_0005_auto_20210326_2102'), ('erp', '0002_auto_20210329_2029'), ('erp', '0003_auto_20210329_2035'), ('erp', '0004_auto_20210329_2040'), ('erp', '0005_orderall_ordercut_orderglue_orderpack_orderpcut_orderprint_orderstuff_orderweld'), ('erp', '0006_auto_20210329_2057')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shortname', models.CharField(max_length=20)),
                ('codename', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Other', 'Other')], default='Customer', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Lead', 'Lead'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('VAT_Number', models.CharField(blank=True, default='', max_length=40)),
                ('tax_status', models.CharField(blank=True, default='', max_length=100)),
                ('office_notes', models.TextField(blank=True, default='')),
                ('order_notes', models.TextField(blank=True, default='')),
                ('manufacture_notes', models.TextField(blank=True, default='')),
                ('delivery_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order')),
                ('OD', models.DateField(blank=True, null=True)),
                ('LD', models.DateField(blank=True, null=True)),
                ('LD_S', models.BooleanField(default=False, help_text='Strict')),
                ('CD', models.DateField(blank=True, null=True)),
                ('CD_C', models.BooleanField(default=False, help_text='confirmed')),
                ('delivered', models.BooleanField(default=False)),
                ('invoiced', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='erp.company')),
                ('container', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='erp.container')),
            ],
            bases=(models.Model, erp.models.order.OrderTotalSummaryMethods),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('SKU', models.CharField(blank=True, default='', max_length=20)),
                ('barcode', models.CharField(blank=True, default='', max_length=20)),
                ('overprints', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDisplayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Product Display Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30)),
                ('print', models.BooleanField(default=False)),
                ('cut', models.BooleanField(default=False)),
                ('weld', models.BooleanField(default=False)),
                ('stuff', models.BooleanField(default=False)),
                ('pack', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='erp.productdisplaycategory')),
            ],
        ),
        migrations.CreateModel(
            name='SpecNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, choices=[('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True)),
                ('choice', models.CharField(blank=True, choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True)),
                ('note', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.product')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranges', to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20)),
                ('note', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productnotes', to='erp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='erp.producttype'),
        ),
        migrations.CreateModel(
            name='OrderNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notebag', to='erp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20)),
                ('note', models.TextField()),
                ('highlight', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordernoteitems', to='erp.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20)),
                ('note', models.TextField()),
                ('highlight', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordernotes', to='erp.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('xprice', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('tally_print', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_cut', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_weld', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_stuff', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_pack', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('print_total', models.PositiveSmallIntegerField(default=0, verbose_name='printed')),
                ('cut_total', models.PositiveSmallIntegerField(default=0, verbose_name='cut')),
                ('weld_total', models.PositiveSmallIntegerField(default=0, verbose_name='welded')),
                ('stuff_total', models.PositiveSmallIntegerField(default=0, verbose_name='stuffed')),
                ('pack_total', models.PositiveSmallIntegerField(default=0, verbose_name='packed')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.product')),
            ],
            bases=(erp.models.orderitem.OrderItemRelatedModelMethods, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('office_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=60)),
                ('contact_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='erp.company')),
            ],
            options={
                'ordering': ('company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVOICE', 'Invoice'), ('DELIVERY', 'Delivery')], default='INVOICE', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='erp.company')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'type', 'title'), name='unique_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_item'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_contact'),
        ),
        migrations.CreateModel(
            name='OrderItemProxy',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='Orderall',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order all',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Ordercut',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order cut',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderprint',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order print',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderweld',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order weld',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderglue',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order glue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderpack',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order pack',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderpvc_cut',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order pvc_cut',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderstuff',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order stuff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='glue_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='glued'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pcut_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='pvc_cut'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tally_glue',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='tally'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tally_pcut',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='tally'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='glue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='pcut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pvc_cut', 'pvc_cut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordernoteitem',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pvc_cut', 'pvc_cut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productnote',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pvc_cut', 'pvc_cut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='choice',
            field=models.CharField(blank=True, choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('pvc_cut', 'pvc_cut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='process',
            field=models.CharField(blank=True, choices=[('print', 'print'), ('pvc_cut', 'pvc_cut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Orderpvc_cut',
        ),
        migrations.CreateModel(
            name='Orderpcut',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order pcut',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pcut', 'pcut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordernoteitem',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pcut', 'pcut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productnote',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pcut', 'pcut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='choice',
            field=models.CharField(blank=True, choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('pcut', 'pcut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='process',
            field=models.CharField(blank=True, choices=[('print', 'print'), ('pcut', 'pcut'), ('cut', 'cut'), ('weld', 'weld'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pcut', 'pcut'), ('weld', 'weld'), ('cut', 'cut'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordernoteitem',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pcut', 'pcut'), ('weld', 'weld'), ('cut', 'cut'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productnote',
            name='process',
            field=models.CharField(choices=[('print', 'print'), ('pcut', 'pcut'), ('weld', 'weld'), ('cut', 'cut'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack'), ('all', 'all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='choice',
            field=models.CharField(blank=True, choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('pcut', 'pcut'), ('weld', 'weld'), ('cut', 'cut'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='process',
            field=models.CharField(blank=True, choices=[('print', 'print'), ('pcut', 'pcut'), ('weld', 'weld'), ('cut', 'cut'), ('glue', 'glue'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productnote',
            name='note',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='OrderItemProxy',
        ),
        migrations.CreateModel(
            name='OrderItemProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.RenameModel(
            old_name='Container',
            new_name='Batch',
        ),
        migrations.DeleteModel(
            name='Orderall',
        ),
        migrations.DeleteModel(
            name='Ordercut',
        ),
        migrations.DeleteModel(
            name='Orderglue',
        ),
        migrations.DeleteModel(
            name='Orderpack',
        ),
        migrations.DeleteModel(
            name='Orderpcut',
        ),
        migrations.DeleteModel(
            name='Orderprint',
        ),
        migrations.DeleteModel(
            name='Orderstuff',
        ),
        migrations.DeleteModel(
            name='Orderweld',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='container',
            new_name='batch',
        ),
        migrations.CreateModel(
            name='Orderall',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order all',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Ordercut',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order cut',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderglue',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order glue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderpack',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order pack',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderpcut',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order pcut',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderprint',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order print',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderstuff',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order stuff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='Orderweld',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Order weld',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
    ]
