# Generated by Django 3.1.7 on 2021-03-08 10:36

from django.db import migrations, models
import django.db.models.deletion
import erp.models.order
import erp.models.orderitem


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('DD', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ('-DD',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shortname', models.CharField(max_length=20)),
                ('codename', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Other', 'Other')], default='Customer', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Lead', 'Lead'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('VAT_Number', models.CharField(blank=True, default='', max_length=40)),
                ('tax_status', models.CharField(blank=True, default='', max_length=100)),
                ('office_notes', models.TextField(blank=True, default='')),
                ('order_notes', models.TextField(blank=True, default='')),
                ('manufacture_notes', models.TextField(blank=True, default='')),
                ('delivery_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order')),
                ('OD', models.DateField(blank=True, null=True)),
                ('LD', models.DateField(blank=True, null=True)),
                ('LD_S', models.BooleanField(default=False, help_text='Strict')),
                ('CD', models.DateField(blank=True, null=True)),
                ('CD_C', models.BooleanField(default=False, help_text='confirmed')),
                ('delivered', models.BooleanField(default=False)),
                ('invoiced', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('xorder_notes', models.TextField(blank=True, default='---press update to copy STD notes---')),
                ('xmanufacture_notes', models.TextField(blank=True, default='---press update to copy STD notes---')),
                ('xdelivery_notes', models.TextField(blank=True, default='---press update to copy STD notes---')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='erp.company')),
                ('container', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='erp.container')),
            ],
            options={
                'ordering': ('LD',),
            },
            bases=(models.Model, erp.models.order.OrderTotalSummaryMethods),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('category', models.CharField(choices=[('CM', 'CM'), ('ARM', 'ARM'), ('XPVC', 'XPVC'), ('M', 'M'), ('SPRUNG', 'SPRUNG'), ('OTHER', 'OTHER')], max_length=20)),
                ('print', models.BooleanField(default=False)),
                ('cut', models.BooleanField(default=False)),
                ('weld', models.BooleanField(default=False)),
                ('stuff', models.BooleanField(default=False)),
                ('pack', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('print_notes', models.TextField(blank=True, default='')),
                ('cut_notes', models.TextField(blank=True, default='')),
                ('pack_notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('SKU', models.CharField(blank=True, default='', max_length=20)),
                ('barcode', models.CharField(blank=True, default='', max_length=20)),
                ('overprint', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='erp.company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='erp.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('xprice', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('xnotes', models.TextField(blank=True, default='')),
                ('xprint_notes', models.TextField(blank=True, default='', help_text='xPrint Notes')),
                ('xcut_notes', models.TextField(blank=True, default='')),
                ('xpack_notes', models.TextField(blank=True, default='')),
                ('tally_print', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_cut', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_weld', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_stuff', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('tally_pack', models.CharField(blank=True, default='', max_length=120, verbose_name='tally')),
                ('print_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cut_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weld_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stuff_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pack_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('item_complete', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.product')),
            ],
            bases=(models.Model, erp.models.orderitem.OrderItemRelatedModelMethods, erp.models.orderitem.OrderItemTotalSummaryMethods),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('office_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=60)),
                ('contact_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='erp.company')),
            ],
            options={
                'ordering': ('company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BatchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchorders', to='erp.batch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batchorders', to='erp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVOICE', 'Invoice'), ('DELIVERY', 'Delivery')], default='INVOICE', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='erp.company')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderItemAdminView',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='OrderItemPrint',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='OrderItemWorksView',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Test Order Items View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='WorksCutView',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Cut View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='WorksPrintView',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Print View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='WorksWeldView',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Weld View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'type', 'title'), name='unique_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_item'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_contact'),
        ),
        migrations.AddConstraint(
            model_name='batchorder',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='unique_batch_order'),
        ),
        migrations.CreateModel(
            name='OrderItemCut',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitemprint',),
        ),
        migrations.CreateModel(
            name='OrderItemPack',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitemprint',),
        ),
        migrations.CreateModel(
            name='OrderItemStuff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitemprint',),
        ),
        migrations.CreateModel(
            name='OrderItemWeld',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitemprint',),
        ),
    ]
