# Generated by Django 3.1.7 on 2021-03-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemOps',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='OrderOps',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Operations View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
    ]
