# Generated by Django 3.1.7 on 2021-03-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_orderitemops_orderops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemWorksView',
        ),
    ]
