# Generated by Django 3.1.5 on 2021-02-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210226_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20)),
                ('note', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
