# Generated by Django 3.1.7 on 2021-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_delete_orderitemworksview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorksCutView',
        ),
        migrations.DeleteModel(
            name='WorksPrintView',
        ),
        migrations.DeleteModel(
            name='WorksWeldView',
        ),
        migrations.CreateModel(
            name='OrderCut',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Cut View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='OrderPack',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Pack View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='OrderPrint',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Print View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='OrderStuff',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Stuff View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='OrderWeld',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Works Weld View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cut_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pack_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='print_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stuff_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weld_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
