# Generated by Django 3.1.5 on 2021-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210226_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
        migrations.DeleteModel(
            name='MyDummy',
        ),
        migrations.DeleteModel(
            name='OrderItem_adminview',
        ),
        migrations.DeleteModel(
            name='PrintOrder',
        ),
        migrations.CreateModel(
            name='OrderItemWorksView',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.CreateModel(
            name='WorksTestPrintOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='tally',
            new_name='tally_print',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tally_cut',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tally_pack',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tally_stuff',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tally_weld',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='LD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='LD_S',
            field=models.BooleanField(default=False, help_text='Strict'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='type',
            field=models.CharField(choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack'), ('SPLASH', 'SPLASH'), ('CM', 'CM'), ('M', 'M')], max_length=20),
        ),
    ]
