# Generated by Django 3.1.7 on 2021-03-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210308_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='print_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='done'),
        ),
    ]
