# Generated by Django 3.1.7 on 2021-03-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210309_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='overprint',
            new_name='overprints',
        ),
    ]
