# Generated by Django 3.1.7 on 2021-03-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210311_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchOrder',
        ),
    ]
