# Generated by Django 3.1.5 on 2021-03-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210227_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpsView',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Operations View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Test Order Items View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cutx',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='xprint_notes',
            field=models.TextField(blank=True, default='', help_text='xPrint Notes'),
        ),
    ]
