# Generated by Django 3.1.7 on 2021-03-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_delete_batchorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
