# Generated by Django 3.1.5 on 2021-03-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20210302_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='erp.container'),
            preserve_default=False,
        ),
    ]
