# Generated by Django 3.1.7 on 2021-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_delete_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemTemplate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cut_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='cut'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pack_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='packed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='print_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='printed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stuff_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='stuffed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weld_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='welded'),
        ),
    ]
