# Generated by Django 3.1.7 on 2021-03-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20210314_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='code',
        ),
    ]
