# Generated by Django 3.1.7 on 2021-03-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_remove_producttype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='category',
        ),
        migrations.AddField(
            model_name='producttype',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='erp.productcategory'),
        ),
    ]
