# Generated by Django 3.1.7 on 2021-03-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20210314_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='category2',
            new_name='category',
        ),
    ]
