# Generated by Django 3.1.7 on 2021-03-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20210314_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductDisplayCategory',
        ),
        migrations.AlterModelOptions(
            name='productdisplaycategory',
            options={'verbose_name_plural': ' Product Display Categories'},
        ),
    ]
