# Generated by Django 3.1.7 on 2021-03-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20210314_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.order')),
            ],
            bases=('erp.order',),
        ),
        migrations.CreateModel(
            name='SpecNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack'), ('CM', 'CM'), ('splash', 'splash'), ('boxes', 'boxes'), ('postal charge', 'postal charge'), ('extra charge', 'extra charge'), ('M', 'M')], max_length=20)),
                ('note', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.company')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.CreateModel(
            name='OrderItemview',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Order Items Overview',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('erp.orderitem',),
        ),
        migrations.AlterModelOptions(
            name='orderitemadminview',
            options={'verbose_name': 'Order Item'},
        ),
        migrations.AlterModelOptions(
            name='orderops',
            options={'verbose_name_plural': 'Operations Order View'},
        ),
    ]
