# Generated by Django 3.1.7 on 2021-03-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20210314_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='specnote',
            name='choice',
            field=models.CharField(blank=True, choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack'), ('CM', 'CM'), ('splash', 'splash'), ('boxes', 'boxes'), ('postal charge', 'postal charge'), ('extra charge', 'extra charge'), ('M', 'M')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specnote',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specnotes', to='erp.producttype'),
        ),
    ]
