# Generated by Django 3.1.7 on 2021-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_auto_20210314_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='specnote',
            name='process',
            field=models.CharField(blank=True, choices=[('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
    ]
