# Generated by Django 3.1.7 on 2021-03-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_specnote_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specnote',
            name='choice',
            field=models.CharField(blank=True, choices=[('office', 'office'), ('delivery', 'delivery'), ('all', 'all'), ('operations', 'operations'), ('print', 'print'), ('cut', 'cut'), ('weld', 'weld'), ('stuff', 'stuff'), ('pack', 'pack')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notebag', to='erp.order')),
            ],
        ),
    ]
